name: Build packages for OpenWrt with patches
on:
  workflow_dispatch:
    inputs:
      menuconfig:
        description: 'Run make menuconfig instead of using diffconfigs'
        required: false
        default: false
        type: boolean
  push:
jobs:
  build:
    strategy:
      matrix:
        target:
          - series: mediatek
            arch: mt7622
            version: 23.05.4
          - series: ramips
            arch: mt7621
            version: 23.05.4
    env:
      VERSION: ${{ matrix.target.version }}
      TARGET: ${{ matrix.target.series }}/${{ matrix.target.arch }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: this_repo
        
      - name: Calc packages-to-build checkcum
        id: ptb
        run: |
          cd this_repo
          # Package To Build
          echo "PTB_CHECKSUM=$(md5sum packages-to-build.list | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - name: Get OpenWrt SDK checksum and URL
        id: prepare
        run: |
          checksum_url="https://downloads.openwrt.org/releases/${{ matrix.target.version }}/targets/$TARGET/sha256sums"
          wget $checksum_url
          sdk_filename=$(grep sdk sha256sums | awk -F'*' '{print $2}')
          sdk_checksum=$(grep sdk sha256sums | awk -F' ' '{print $1}')
          sdk_dir=$(basename $sdk_filename .tar.xz)
          echo "SDK_CHECKSUM=$sdk_checksum" >> $GITHUB_OUTPUT
          echo "SDK_FILENAME=$sdk_filename" >> $GITHUB_OUTPUT
          echo "SDK_DIR=$sdk_dir" >> $GITHUB_OUTPUT

      - name: Restore cache
        id: restore_sdk
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-openwrt-sdk-${{ matrix.target.version }}-${{ matrix.target.series }}-${{ matrix.target.arch }}-${{ steps.prepare.outputs.SDK_CHECKSUM }}-ptb-${{ steps.ptb.outputs.PTB_CHECKSUM }}
          path: |
            ${{ steps.prepare.outputs.SDK_DIR }}
            ~/.cache/ccache

      - name: Download OpenWrt SDK
        if: steps.restore_sdk.outputs.cache-hit != 'true'
        run: |
          sdk_url="https://downloads.openwrt.org/releases/${{ matrix.target.version }}/targets/$TARGET/${{ steps.prepare.outputs.SDK_FILENAME }}"
          wget -q $sdk_url

      - name: Deploy SDK
        if: steps.restore_sdk.outputs.cache-hit != 'true'
        run: |
          tar xf ${{ steps.prepare.outputs.SDK_FILENAME }}
          cd ${{ steps.prepare.outputs.SDK_DIR }}
          
          # Insert custom feeds
          tmp_conf=$(mktemp)
          cp ../this_repo/custom-feeds/${VERSION%.*}.conf $tmp_conf
          echo >> $tmp_conf
          cat ./feeds.conf.default >> $tmp_conf
          cp $tmp_conf ./feeds.conf.default

          ./scripts/feeds update -a
          cat ../this_repo/packages-to-build.list | xargs -n1 ./scripts/feeds install
          make defconfig

          # Pre-compile some heavy common packages
          make package/toolchain/compile -j
          make package/kernel/linux/compile -j

      - name: Cache
        uses: actions/cache/save@v4
        with:
          key: ${{ runner.os }}-openwrt-sdk-${{ matrix.target.version }}-${{ matrix.target.series }}-${{ matrix.target.arch }}-${{ steps.prepare.outputs.SDK_CHECKSUM }}-ptb-${{ steps.ptb.outputs.PTB_CHECKSUM }}
          path: |
           ${{ steps.prepare.outputs.SDK_DIR }}
           ~/.cache/ccache
      
      - name: Deploy .config
        id: deploy_config
        run: |
          cp this_repo/diffconfigs/${{ matrix.target.version }}-${{ matrix.target.series }}-${{ matrix.target.arch }}.diffconfig ${{ steps.prepare.outputs.SDK_DIR }}/.config
        continue-on-error: true
          
      - name: make menuconfig
        if: ${{ inputs.menuconfig }} || ${{ steps.deploy_config.outcome != 'success' }}
        uses: mxschmitt/action-tmate@v3

      - name: Build
        id: build
        env:
          SDK_DIR: ${{ steps.prepare.outputs.SDK_DIR }}
        run: |
          cd $SDK_DIR
          make defconfig
          cat ../this_repo/packages-to-build.list | xargs -I'{}' make 'package/{}/compile' -j
          mkdir ../ipk/
          cat ../this_repo/artifact-patterns.list | xargs -n1 find bin/ -name | xargs -I'{}' cp '{}' ../ipk/

      - name: Upload ipks
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-${{ matrix.target.VERSION }}-${{ matrix.target.series }}-${{ matrix.target.arch }}
          path: ipk/*.ipk
      
      - name: Generate diffconfig
        run: |
          cd ${{ steps.prepare.outputs.SDK_DIR }}
          ./scripts/diffconfig.sh > ../${{ matrix.target.version }}-${{ matrix.target.series }}-${{ matrix.target.arch }}.config
      
      - name: Upload .config
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-${{ matrix.target.VERSION }}-${{ matrix.target.series }}-${{ matrix.target.arch }}-diffconfig
          path: ${{ matrix.target.version }}-${{ matrix.target.series }}-${{ matrix.target.arch }}.config
