name: Build packages for OpenWrt with patches
on: [push, workflow_dispatch]
jobs:
  build:
    strategy:
      matrix:
        version: [23.05.4]
        target0: [mediatek]
        target1: [mt7622]
    runs-on: ubuntu-latest
    steps:
      - name: Get OpenWrt SDK checksum and URL
        id: prepare
        env:
          VERSION: ${{ matrix.version }}
          TARGET: ${{ matrix.target0 }}/${{ matrix.target1 }}
        run: |
          checksum_url="https://downloads.openwrt.org/releases/$VERSION/targets/$TARGET/sha256sums"
          wget $checksum_url
          sdk_filename=$(grep sdk sha256sums | awk -F'*' '{print $2}')
          sdk_checksum=$(grep sdk sha256sums | awk -F' ' '{print $1}')
          sdk_dir=$(basename $sdk_filename .tar.xz)
          echo "SDK_CHECKSUM=$sdk_checksum" >> $GITHUB_OUTPUT
          echo "SDK_FILENAME=$sdk_filename" >> $GITHUB_OUTPUT
          echo "SDK_DIR=$sdk_dir" >> $GITHUB_OUTPUT

      - name: Restore SDK cache
        id: restore_sdk
        uses: actions/cache/restore@v4
        with:
          key: openwrt-sdk-${{ matrix.version }}-${{ matrix.target0 }}-${{ matrix.target1 }}-${{ steps.prepare.outputs.SDK_CHECKSUM }}
          path: ${{ steps.prepare.outputs.SDK_DIR }}

      - name: Download OpenWrt SDK
        if: steps.restore_sdk.outputs.cache-hit != 'true'
        env:
          VERSION: ${{ matrix.version }}
          SDK_FILENAME: ${{ steps.prepare.outputs.SDK_FILENAME }}
          TARGET: ${{ matrix.target0 }}/${{ matrix.target1 }}
        run: |
          sdk_url="https://downloads.openwrt.org/releases/$VERSION/targets/$TARGET/$SDK_FILENAME"
          wget -q $sdk_url

      - name: Deploy SDK
        if: steps.restore_sdk.outputs.cache-hit != 'true'
        env:
          SDK_FILENAME: ${{ steps.prepare.outputs.SDK_FILENAME }}
          SDK_DIR: ${{ steps.prepare.outputs.SDK_DIR }}
        run: |
          tar -xJf $SDK_FILENAME
          cd $SDK_DIR
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Cache SDK
        id: cache_sdk
        uses: actions/cache/save@v4
        with:
          key: openwrt-sdk-${{ matrix.version }}-${{ matrix.target0 }}-${{ matrix.target1 }}-${{ steps.prepare.outputs.SDK_CHECKSUM }}
          path: ${{ steps.prepare.outputs.SDK_DIR }}

      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: this_repo

      - name: Build
        id: build
        env:
          TARGET: ${{ matrix.target0 }}-${{ matrix.target1 }}
        run: |
          cd $SDK_DIR

          cp ../this_repo/diffconfigs/$TARGET $SDK_DIR/.config
          make defconfig

          cp ../this_repo/build* ./
          chmod +x build.py
          mkdir ../ipk/
          ./build.py ../ipk/

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-${{ matrix.version }}-${{ matrix.target0 }}-${{ matrix.target1 }}
          path: ipk/*.ipk
