name: Build OpenWrt Packages
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'OpenWrt version to build, including revision number'
        required: true
        type: string
        default: 23.05.5
      target:
        description: 'Target to build for'
        required: true
        type: choice
        options:
          - ath79-nand
          - mediatek-mt7622
          - ramips-mt7621
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: this_repo
      
      - name: Restore SDK tar
        id: restore_sdk_tar
        uses: actions/cache/restore@v4
        with:
          key: openwrt-sdk-${{ inputs.version }}-${{ inputs.target }}

      - name: Download SDK tar
        id: download_sdk_tar
        if: ${{ steps.restore_sdk_tar.outputs.cache-hit != 'true' }}
        run: |
          series=$(echo ${{ inputs.target }} | cut -d'-' -f1)
          arch=$(echo ${{ inputs.target }} | cut -d'-' -f2)

          base_url="https://downloads.openwrt.org/releases/${{ inputs.version }}/targets/$series/$arch"

          checksum_file_url="$base_url/sha256sums"
          wget -q $checksum_file_url

          sdk_filename=$(grep sdk sha256sums | cut -d'*' -f2)
          sdk_url="$base_url/$sdk_filename"
          echo "Downloading SDK from $sdk_url"
          wget -q $sdk_url

          echo "SDK_FILENAME=$sdk_filename" >> $GITHUB_OUTPUT
      
      - name: Cache SDK tar
        uses: actions/cache/save@v4
        with:
          key: openwrt-sdk-${{ inputs.version }}-${{ inputs.target }}
          path: |
            ${{ steps.download_sdk_tar.outputs.SDK_FILENAME }}
      
      - name: Prepare SDK
        run: |
          tar xf $sdk_filename
          sdk_dir=$(tar tf $sdk_filename | head -n1 | cut -d'/' -f1)

          # Prepare feeds.conf.default
          version=${{ inputs.version }}
          feeds_in="this_repo/.github/feeds.conf.default.in"
          sed "s/<version>/${version::-2}/g" $feeds_in > $sdk_dir/feeds.conf.default

          cd $sdk_dir
          ./scripts/feeds update -a
          cat this_repo/.github/packages-to-build.list \
            | xargs -n1 ./scripts/feeds install
          
          echo "SDK_DIR=$sdk_dir" >> $GITHUB_ENV

      - name: Prepare .config using tmate
        uses: mxschmitt/action-tmate@v3
      
      - name: Build packages
        run: |
          cd $SDK_DIR
          cat this_repo/.github/package-to-build.list \
            | xargs -I'{}' make package/{}/compile -j
          
          # Copy packages to artifacts
          mkdir -p ../artifacts/packages
          cat this_repo/.github/artifact-patterns.list \
            | xargs -n1 find bin -name \
            | xargs -I'{}' cp '{}' ../artifacts/packages

          # Generate diffconfig and save it as an artifact
          ./scripts/diffconfig.sh > ../artifacts/openwrt-${{ inputs.version }}-${{ inputs.target }}.diffconf
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-${{ inputs.version }}-${{ inputs.target }}
          path: artifacts
        