name: Build OpenWrt Packages
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'OpenWrt version to build, including revision number'
        required: true
        type: string
        default: 23.05.5
      target:
        description: 'Target to build for'
        required: true
        type: choice
        options:
          - mediatek-mt7622
          - ramips-mt7621
          - ath79-nand
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare SDK
        run: |
          series=$(echo ${{ github.event.inputs.target }} | cut -d'-' -f1)
          arch=$(echo ${{ github.event.inputs.target }} | cut -d'-' -f2)

          base_url="https://downloads.openwrt.org/releases/${{ inputs.version }}/targets/$series/$arch"

          checksum_file_url="$base_url/sha256sums"
          wget -q $checksum_file_url

          echo "Downloading SDK from $base_url"
          sdk_filename=$(grep sdk sha256sums | cut -d'*' -f2)
          sdk_url="$base_url/$sdk_filename"
          wget -q $sdk_url

          tar xf $sdk_filename
          sdk_dir=$(tar tf $sdk_filename | head -n1 | cut -d'/' -f1)

          # Prepare feeds.conf.default
          version=${{ inputs.version }}
          feeds_in=${{ github.action_path }}/.github/feeds.conf.default.in
          sed "s/<version>/${version::-2}/g" $feeds_in > $sdk_dir/feeds.conf.default

          cd $sdk_dir
          ./scripts/feeds update -a
          cat ${{ github.action_path }}/.github/packages-to-build.list \
            | xargs -n1 ./scripts/feeds install
          
          echo "SDK_DIR=$sdk_dir" >> $GITHUB_ENV

      - name: Prepare .config using tmate
        uses: mxschmitt/action-tmate@v3
      
      - name: Build packages
        run: |
          cd $SDK_DIR
          cat ${{ github.action_path }}/.github/package-to-build.list \
            | xargs -I'{}' make package/{}/compile -j
          
          # Copy packages to artifacts
          mkdir -p ../artifacts/packages
          cat ${{ github.action_path }}/.github/artifact-patterns.list \
            | xargs -n1 find bin -name \
            | xargs -I'{}' cp '{}' ../artifacts/packages

          # Generate diffconfig and save it as an artifact
          ./scripts/diffconfig.sh > ../artifacts/openwrt-${{ inputs.version }}-${{ inputs.target }}.diffconf
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-${{ inputs.version }}-${{ inputs.target }}
          path: artifacts
        