name: Build miniupnpd for OpenWrt with patches
on: [push, workflow_dispatch]
env:
  PATCH: https://github.com/AquanJSW/miniupnpd/releases/download/modify-2.3.3/000-bypass-reserved-ip.patch
jobs:
  build:
    strategy:
      matrix:
        device:
          - ax6s
        sdk:
          - https://downloads.openwrt.org/releases/23.05.4/targets/mediatek/mt7622/openwrt-sdk-23.05.4-mediatek-mt7622_gcc-12.3.0_musl.Linux-x86_64.tar.xz
    runs-on: ubuntu-latest
    steps:
      - name: Download OpenWrt SDK
        run: |
          wget ${{ matrix.sdk }}
          FILENAME=$(basename ${{ matrix.sdk }})
          DIR_NAME=$(basename ${{ matrix.sdk }} .tar.xz)
          tar -xJf $FILENAME
          echo "SDK_DIR=$DIR_NAME" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: this_repo

      - name: Build
        id: build
        run: |
          cp this_repo/diffconfigs/miniupnpd-${{ matrix.device }} $SDK_DIR/.config
          cd $SDK_DIR
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          wget -o feeds/packages/net/miniupnpd/patches/000-bypass-reserved-ip.patch $PATCH
          make defconfig
          make package/miniupnpd/compile -j
          IPK_FILE=$(find bin/packages -name "miniupnpd*.ipk" -type f)
          cp $IPK_FILE ${{ github.workspace }}
          IPK_NAME=$(basename $IPK_FILE)
          echo "IPK_NAME=$IPK_NAME" >> $GITHUB_OUTPUT

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.IPK_NAME }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.IPK_NAME }}
